/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tris_;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author andrea
 */
public class scegliplayer extends javax.swing.JFrame {

    
    private boolean Xaccsel = true;
    private boolean Oaccsel = false;
    
    
    /**
     * 
     * 
     * Creates new form scegliplayer
     */
    public scegliplayer() {
        initComponents();
        setLocationRelativeTo(null);
        
        try {
            File file = new File("theme.txt");
            Scanner leggi = new Scanner(file);
            while(leggi.hasNextLine()) {
                String tmp = leggi.nextLine();
                if (tmp.equals("light")) {
                    jPanel1.setBackground(new Color(0, 204, 255));
                } else if (tmp.equals("dark")) {
                    jPanel1.setBackground(new Color(0, 153, 255 ));
                } else if (tmp.equals("auto")) {
                    if (Detector.isDarkMode()==true) {
                        jPanel1.setBackground(new Color(0, 153, 255 ));
                    } else {
                        jPanel1.setBackground(new Color(0, 204, 255));
                    }
                }
            } 
        } catch (FileNotFoundException ex) {
                Logger.getLogger(customization.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        try {
                
          File myObj = new File("nick.txt");
          Scanner myReader = new Scanner(myObj);  
          while (myReader.hasNextLine()) {
            String tmp = myReader.nextLine();
            xname.setText(tmp);
            xname.setEditable(false);
          }
          
   
          myReader.close();
        } catch (FileNotFoundException e) {
          System.out.println("An error occurred.");
          e.printStackTrace();
        } 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        opicon = new javax.swing.JButton();
        xpicon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        oname = new javax.swing.JTextField();
        xname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setForeground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        opicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tris_/avataregrandenocolori.png"))); // NOI18N
        opicon.setContentAreaFilled(false);
        opicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opiconActionPerformed(evt);
            }
        });
        jPanel1.add(opicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 236, -1, 90));

        xpicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tris_/avatargrande2.png"))); // NOI18N
        xpicon.setContentAreaFilled(false);
        xpicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xpiconActionPerformed(evt);
            }
        });
        jPanel1.add(xpicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, 100));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Players");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        oname.setBackground(java.awt.Color.darkGray);
        oname.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        oname.setForeground(new java.awt.Color(255, 255, 255));
        oname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        oname.setText("GUEST");
        oname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onameActionPerformed(evt);
            }
        });
        jPanel1.add(oname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 210, 60));

        xname.setBackground(java.awt.Color.darkGray);
        xname.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        xname.setForeground(new java.awt.Color(255, 255, 255));
        xname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xname.setText("ACCOUNT");
        jPanel1.add(xname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 210, 60));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel4.setText("O PLAYER:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel5.setText("X PLAYER:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tris_/play.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onameActionPerformed

    private void opiconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opiconActionPerformed
        // TODO add your handling code here:
        
        selezione();
        
        
    }//GEN-LAST:event_opiconActionPerformed

    private void xpiconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xpiconActionPerformed
        // TODO add your handling code here:
        selezione();
    }//GEN-LAST:event_xpiconActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String X = xname.getText();
        String O = oname.getText();
        
        try (FileWriter scrivi = new FileWriter("xname.txt")) {
                            scrivi.write(X);
                           
                            
                        } catch (IOException e) {

                        } 
        try (FileWriter scrivi = new FileWriter("oname.txt")) {
                            scrivi.write(O);
                           
                        } catch (IOException e) {

                        } 
        if (Xaccsel == true) {
            try (FileWriter scrivi = new FileWriter("acc.txt")) {
                            scrivi.write("xacc");
                           
                        } catch (IOException e) {

                        } 
        } else {
            try (FileWriter scrivi = new FileWriter("acc.txt")) {
                            scrivi.write("oacc");
                           
                        } catch (IOException e) {

                        } 
        }
        
        
        this.setVisible(false);
        new multiplayer().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void selezione() {
        oname.setEditable(true);
        xname.setEditable(true);
        if (Xaccsel == true) {
            xpicon.setIcon(new ImageIcon(getClass().getResource("avataregrandenocolori.png")));
            opicon.setIcon(new ImageIcon(getClass().getResource("avatargrande2.png")));
            Xaccsel = false;
            Oaccsel = true;
            
            xname.setText("GUEST");
            //oname.setText("ACCOUNT");
            
            try {
                
          File myObj = new File("nick.txt");
          Scanner myReader = new Scanner(myObj);  
          while (myReader.hasNextLine()) {
            String tmp = myReader.nextLine();
            oname.setText(tmp);
            oname.setEditable(false);
            
          }
          
   
          myReader.close();
        } catch (FileNotFoundException e) {
          System.out.println("An error occurred.");
          e.printStackTrace();
        } 
            
            //System.out.println(Xaccsel + "" + Oaccsel);
        } else
        if (Oaccsel == true) {
            xpicon.setIcon(new ImageIcon(getClass().getResource("avatargrande2.png")));
            opicon.setIcon(new ImageIcon(getClass().getResource("avataregrandenocolori.png")));
            Xaccsel = true;
            Oaccsel = false;
            oname.setText("GUEST");
            //xname.setText("ACCOUNT");
            
             try {
                
          File myObj = new File("nick.txt");
          Scanner myReader = new Scanner(myObj);  
          while (myReader.hasNextLine()) {
            String tmp = myReader.nextLine();
            xname.setText(tmp);
            xname.setEditable(false);
          }
          
   
          myReader.close();
        } catch (FileNotFoundException e) {
          System.out.println("An error occurred.");
          e.printStackTrace();
        } 
            //System.out.println(Xaccsel + "" + Oaccsel);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scegliplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scegliplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scegliplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scegliplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scegliplayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField oname;
    private javax.swing.JButton opicon;
    private javax.swing.JTextField xname;
    private javax.swing.JButton xpicon;
    // End of variables declaration//GEN-END:variables
}
